### ISSUE TITLE
Can't run from CLI in Ubuntu 20.04

### ISSUE THREAD

**Issue by cibermanchego** [Lissy93/wapalyzer#1]
Hi, first of all, thank you for this, really nice reviving this tool.
Disclaimer: I have zero experience with nodejs or yarn.

I installed nodejs 18.17.1 and latest yarn.
Then clone the repo and run:
yarn install -> works OK
yarn run link -> get this error:
`yarn run v1.22.19
error Command "link" not found. Did you mean "lint"?`

I googled the error but I can't find a clear solution or reason for the error.
When I try to run from CLI, I noticed that I don't have the npm directory under drivers, only webextensions.

I don't want to use the Chrome or Firefox extensions, is there a way to make this work?
Thank you again for sharing this great tool

**Comment by juneeighteen** [comment]
It looks like the command might be `yarn link` instead of `yarn run link`
