### ISSUE TITLE
Manifests are missing

### ISSUE THREAD

**Issue by kim3-sudo** [Lissy93/wapalyzer#2]
**Platform**
Which platform does the bug apply to?
WebExtension

**Describe the bug**
The manifest files for the web extension is missing.

**To Reproduce**
No files in /src/drivers/webextension except for a single SVG

**Expected behavior**
Installation instructions should allow an unpacked extension to be loaded into Chrome or Firefox per README.md

**Additional context**

**Comment by kingthorin** [comment]
Check the history in that folder, you'll probably find they were removed by the original author and need restoration.
