### ISSUE TITLE
Browsers/zombie.js & Browsers/puppeteer.js

### ISSUE THREAD

**Issue by Martin-Thiele** [Lissy93/wapalyzer#4]
Where are these files?

**Comment by Martin-Thiele** [comment]
[browsers.zip](https://github.com/Lissy93/wapalyzer/files/12845594/browsers.zip)
I found some old versions here https://www.npmjs.com/package/wappalyzer/v/5.9.3. Not sure if they are up to date. Zombie works with it. Puppeteer runs but does not give any result.

_Browser.js_ needs `module.exports = Browser` for this to work.

This project needs a solid makeover and i'm not sure anyone is willing to do it.

**Comment by eli-front** [comment]
+1
